export interface CategoryNode {
  id: string;
  name: string;
  parentId: string | null;
  children: CategoryNode[];
  slug: string;
}

function toSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function buildTree(rows: { id: string; name: string; parentId: string }[]): CategoryNode[] {
  const map = new Map<string, CategoryNode>();
  const roots: CategoryNode[] = [];

  for (const row of rows) {
    map.set(row.id, {
      id: row.id,
      name: row.name,
      parentId: row.parentId || null,
      children: [],
      slug: toSlug(row.name),
    });
  }

  for (const node of map.values()) {
    if (node.parentId && map.has(node.parentId)) {
      map.get(node.parentId)!.children.push(node);
    } else {
      roots.push(node);
    }
  }

  return roots;
}

// Parsed from fasteners_inc_converted_tax.csv
const rawCategories: { id: string; name: string; parentId: string }[] = [
  // Power Tools
  { id: "dds1", name: "Power Tools", parentId: "" },
  { id: "dds2", name: "Drills & Fastening Tools", parentId: "dds1" },
  { id: "dds3", name: "Drills", parentId: "dds2" },
  { id: "dds4", name: "Hammer Drills", parentId: "dds2" },
  { id: "dds5", name: "Impact Drivers", parentId: "dds2" },
  { id: "dds6", name: "Impact Wrenches", parentId: "dds2" },
  { id: "dds7", name: "Screw Guns", parentId: "dds2" },
  { id: "dds8", name: "Saws & Cutting Tools", parentId: "dds1" },
  { id: "dds9", name: "Circular Saws", parentId: "dds8" },
  { id: "dds10", name: "Reciprocating Saws", parentId: "dds8" },
  { id: "dds11", name: "Jig Saws", parentId: "dds8" },
  { id: "dds12", name: "Miter Saws", parentId: "dds8" },
  { id: "dds13", name: "Track Saws", parentId: "dds8" },
  { id: "dds14", name: "Portable Band Saws", parentId: "dds8" },
  { id: "dds15", name: "Cut-Off Saws", parentId: "dds8" },
  { id: "dds16", name: "Grinding, Sanding & Finishing", parentId: "dds1" },
  { id: "dds17", name: "Angle Grinders", parentId: "dds16" },
  { id: "dds18", name: "Die Grinders", parentId: "dds16" },
  { id: "dds19", name: "Sanders", parentId: "dds16" },
  { id: "dds20", name: "Polishers", parentId: "dds16" },
  { id: "dds21", name: "Buffers", parentId: "dds16" },
  { id: "dds22", name: "Outdoor Power Equipment", parentId: "dds1" },
  { id: "dds23", name: "Pressure Washers", parentId: "dds22" },
  { id: "dds24", name: "Blowers", parentId: "dds22" },
  { id: "dds25", name: "String Trimmers", parentId: "dds22" },
  { id: "dds26", name: "Hedge Trimmers", parentId: "dds22" },
  { id: "dds27", name: "Chainsaws", parentId: "dds22" },
  { id: "dds28", name: "Specialty Power Tools", parentId: "dds1" },
  { id: "dds29", name: "Oscillating Multi-Tools", parentId: "dds28" },
  { id: "dds30", name: "Heat Guns", parentId: "dds28" },
  { id: "dds31", name: "Power Planers", parentId: "dds28" },
  { id: "dds32", name: "Power Shears", parentId: "dds28" },
  { id: "dds33", name: "Power Nibblers", parentId: "dds28" },
  { id: "dds34", name: "Mixers", parentId: "dds28" },
  { id: "dds35", name: "Jump Starters", parentId: "dds28" },
  { id: "dds36", name: "Power Tool Kits", parentId: "dds1" },
  { id: "dds37", name: "Combo Kits", parentId: "dds36" },
  { id: "dds38", name: "Concrete & Masonry Tools", parentId: "dds1" },
  { id: "dds39", name: "Rotary Hammers", parentId: "dds38" },
  { id: "dds40", name: "Demolition Hammers", parentId: "dds38" },
  { id: "dds41", name: "Concrete Breakers", parentId: "dds38" },
  { id: "dds42", name: "Electric Jackhammers", parentId: "dds38" },
  { id: "dds43", name: "Concrete Vibrators", parentId: "dds38" },
  { id: "dds44", name: "Concrete Mixers", parentId: "dds38" },
  { id: "dds45", name: "Rebar Cutters & Benders", parentId: "dds38" },

  // Hand Tools
  { id: "dds46", name: "Hand Tools", parentId: "" },
  { id: "dds47", name: "Striking Tools", parentId: "dds46" },
  { id: "dds48", name: "Hammers", parentId: "dds47" },
  { id: "dds49", name: "Mallets", parentId: "dds47" },
  { id: "dds50", name: "Sledgehammers", parentId: "dds47" },
  { id: "dds51", name: "Dead Blow Hammers", parentId: "dds47" },
  { id: "dds52", name: "Wrenches & Ratcheting Tools", parentId: "dds46" },
  { id: "dds53", name: "Combination Wrenches", parentId: "dds52" },
  { id: "dds54", name: "Open-End Wrenches", parentId: "dds52" },
  { id: "dds55", name: "Box-End Wrenches", parentId: "dds52" },
  { id: "dds56", name: "Adjustable Wrenches", parentId: "dds52" },
  { id: "dds57", name: "Ratcheting Wrenches", parentId: "dds52" },
  { id: "dds58", name: "Torque Wrenches", parentId: "dds52" },
  { id: "dds59", name: "Sockets & Accessories", parentId: "dds46" },
  { id: "dds60", name: "Socket Sets", parentId: "dds59" },
  { id: "dds61", name: "Individual Sockets", parentId: "dds59" },
  { id: "dds62", name: "Extensions", parentId: "dds59" },
  { id: "dds63", name: "Adapters", parentId: "dds59" },
  { id: "dds64", name: "Universal Joints", parentId: "dds59" },
  { id: "dds65", name: "Pliers & Cutting Tools", parentId: "dds46" },
  { id: "dds66", name: "Pliers", parentId: "dds65" },
  { id: "dds67", name: "Needle-Nose Pliers", parentId: "dds65" },
  { id: "dds68", name: "Slip-Joint Pliers", parentId: "dds65" },
  { id: "dds69", name: "Locking Pliers", parentId: "dds65" },
  { id: "dds70", name: "Wire Cutters", parentId: "dds65" },
  { id: "dds71", name: "Bolt Cutters", parentId: "dds65" },
  { id: "dds72", name: "Screwdrivers & Hex Keys", parentId: "dds46" },
  { id: "dds73", name: "Screwdrivers", parentId: "dds72" },
  { id: "dds74", name: "Nut Drivers", parentId: "dds72" },
  { id: "dds75", name: "Hex Keys", parentId: "dds72" },
  { id: "dds76", name: "Torx Keys", parentId: "dds72" },
  { id: "dds77", name: "Measuring & Layout Tools", parentId: "dds46" },
  { id: "dds78", name: "Tape Measures", parentId: "dds77" },
  { id: "dds79", name: "Levels", parentId: "dds77" },
  { id: "dds80", name: "Squares", parentId: "dds77" },
  { id: "dds81", name: "Calipers", parentId: "dds77" },
  { id: "dds82", name: "Chalk lines", parentId: "dds77" },
  { id: "dds83", name: "Chalk", parentId: "dds77" },
  { id: "dds84", name: "Marking pencils", parentId: "dds77" },
  { id: "dds85", name: "Markers", parentId: "dds77" },
  { id: "dds86", name: "Clamping & Vises", parentId: "dds46" },
  { id: "dds87", name: "Bar Clamps", parentId: "dds86" },
  { id: "dds88", name: "C-Clamps", parentId: "dds86" },
  { id: "dds89", name: "Spring Clamps", parentId: "dds86" },
  { id: "dds90", name: "Bench Vises", parentId: "dds86" },
  { id: "dds91", name: "Hand Vises", parentId: "dds86" },
  { id: "dds92", name: "Cutting & Shaping Tools", parentId: "dds46" },
  { id: "dds93", name: "Hand Saws", parentId: "dds92" },
  { id: "dds94", name: "Chisels", parentId: "dds92" },
  { id: "dds95", name: "Files", parentId: "dds92" },
  { id: "dds96", name: "Rasps", parentId: "dds92" },
  { id: "dds97", name: "Snips", parentId: "dds92" },
  { id: "dds98", name: "Pry Bars & Lifting Tools", parentId: "dds46" },
  { id: "dds99", name: "Pry Bars", parentId: "dds98" },
  { id: "dds100", name: "Wrecking Bars", parentId: "dds98" },
  { id: "dds101", name: "Crowbars", parentId: "dds98" },
  { id: "dds102", name: "Manual Jacks", parentId: "dds98" },

  // Power Tool Accessories
  { id: "dds103", name: "Power Tool Accessories", parentId: "" },
  { id: "dds104", name: "Blades & Abrasives", parentId: "dds103" },
  { id: "dds105", name: "Circular Saw Blades", parentId: "dds104" },
  { id: "dds106", name: "Reciprocating Saw Blades", parentId: "dds104" },
  { id: "dds107", name: "Jig Saw Blades", parentId: "dds104" },
  { id: "dds108", name: "Band Saw Blades", parentId: "dds104" },
  { id: "dds109", name: "Grinding Wheels", parentId: "dds104" },
  { id: "dds110", name: "Cut-Off Wheels", parentId: "dds104" },
  { id: "dds111", name: "Sanding Discs", parentId: "dds104" },
  { id: "dds112", name: "Flap Discs", parentId: "dds104" },
  { id: "dds113", name: "Wire Wheels", parentId: "dds104" },
  { id: "dds114", name: "Drilling Accessories", parentId: "dds103" },
  { id: "dds115", name: "Twist Drill Bits", parentId: "dds114" },
  { id: "dds116", name: "Masonry Bits", parentId: "dds114" },
  { id: "dds117", name: "Step Bits", parentId: "dds114" },
  { id: "dds118", name: "Hole Saws", parentId: "dds114" },
  { id: "dds119", name: "Auger Bits", parentId: "dds114" },
  { id: "dds120", name: "Fastening Accessories", parentId: "dds103" },
  { id: "dds121", name: "Driver Bits", parentId: "dds120" },
  { id: "dds122", name: "Bit Holders", parentId: "dds120" },
  { id: "dds123", name: "Nut Setters", parentId: "dds120" },
  { id: "dds124", name: "Extensions", parentId: "dds120" },
  { id: "dds125", name: "Batteries & Chargers", parentId: "dds103" },
  { id: "dds126", name: "Tool Batteries", parentId: "dds125" },
  { id: "dds127", name: "Battery Chargers", parentId: "dds125" },
  { id: "dds128", name: "Power Cords & Adapters", parentId: "dds125" },
  { id: "dds129", name: "Replacement Parts & Consumables", parentId: "dds103" },
  { id: "dds130", name: "Carbon Brushes", parentId: "dds129" },
  { id: "dds131", name: "Drive Belts", parentId: "dds129" },
  { id: "dds132", name: "Filters", parentId: "dds129" },
  { id: "dds133", name: "Lubrication", parentId: "dds129" },
  { id: "dds134", name: "Replacement Parts", parentId: "dds129" },

  // Air Tools & Compressors
  { id: "dds135", name: "Air Tools & Compressors", parentId: "" },
  { id: "dds136", name: "Air Compressors", parentId: "dds135" },
  { id: "dds137", name: "Portable Air Compressors", parentId: "dds136" },
  { id: "dds138", name: "Stationary Air Compressors", parentId: "dds136" },
  { id: "dds139", name: "Pneumatic Fastening Tools", parentId: "dds135" },
  { id: "dds140", name: "Air Nailers", parentId: "dds139" },
  { id: "dds141", name: "Air Staplers", parentId: "dds139" },
  { id: "dds142", name: "Air Impact Wrenches", parentId: "dds139" },
  { id: "dds143", name: "Air Ratchets", parentId: "dds139" },
  { id: "dds144", name: "Air Rivet Guns", parentId: "dds139" },
  { id: "dds145", name: "Pneumatic Cutting Tools", parentId: "dds135" },
  { id: "dds146", name: "Air Cut-Off Tools", parentId: "dds145" },
  { id: "dds147", name: "Air Reciprocating Saws", parentId: "dds145" },
  { id: "dds148", name: "Air Shears", parentId: "dds145" },
  { id: "dds149", name: "Air Nibblers", parentId: "dds145" },
  { id: "dds150", name: "Pneumatic Grinding & Finishing", parentId: "dds135" },
  { id: "dds151", name: "Air Die Grinders", parentId: "dds150" },
  { id: "dds152", name: "Air Angle Grinders", parentId: "dds150" },
  { id: "dds153", name: "Air Sanders", parentId: "dds150" },
  { id: "dds154", name: "Air Polishers", parentId: "dds150" },
  { id: "dds155", name: "Air Tool Accessories", parentId: "dds135" },
  { id: "dds156", name: "Air Hoses", parentId: "dds155" },
  { id: "dds157", name: "Hose Reels", parentId: "dds155" },
  { id: "dds158", name: "Couplers & Fittings", parentId: "dds155" },
  { id: "dds159", name: "Regulators", parentId: "dds155" },
  { id: "dds160", name: "Filters", parentId: "dds155" },
  { id: "dds161", name: "Lubricators", parentId: "dds155" },
  { id: "dds162", name: "Blow Guns", parentId: "dds155" },

  // Machine Tools
  { id: "dds163", name: "Machine Tools", parentId: "" },
  { id: "dds164", name: "Metal Cutting Machines", parentId: "dds163" },
  { id: "dds165", name: "Plasma Cutting Machines", parentId: "dds164" },
  { id: "dds166", name: "Laser Cutting Machines", parentId: "dds164" },
  { id: "dds167", name: "Waterjet Cutting Machines", parentId: "dds164" },
  { id: "dds168", name: "Metal Forming Machines", parentId: "dds163" },
  { id: "dds169", name: "Press Brakes", parentId: "dds168" },
  { id: "dds170", name: "Ironworkers", parentId: "dds168" },
  { id: "dds171", name: "Plate Shears", parentId: "dds168" },
  { id: "dds172", name: "Punch Presses", parentId: "dds168" },
  { id: "dds173", name: "Roll Forming Machines", parentId: "dds168" },
  { id: "dds174", name: "Drilling & Boring Machines", parentId: "dds163" },
  { id: "dds175", name: "Drill Presses", parentId: "dds174" },
  { id: "dds176", name: "Radial Drilling Machines", parentId: "dds174" },
  { id: "dds177", name: "Magnetic Drill Presses", parentId: "dds174" },
  { id: "dds178", name: "Boring Machines", parentId: "dds174" },
  { id: "dds179", name: "Grinding & Finishing Machines", parentId: "dds163" },
  { id: "dds180", name: "Surface Grinders", parentId: "dds179" },
  { id: "dds181", name: "Cylindrical Grinders", parentId: "dds179" },
  { id: "dds182", name: "Bench Grinders", parentId: "dds179" },
  { id: "dds183", name: "Belt Grinding Machines", parentId: "dds179" },
  { id: "dds184", name: "Milling Machines", parentId: "dds163" },
  { id: "dds185", name: "Vertical Milling Machines", parentId: "dds184" },
  { id: "dds186", name: "Horizontal Milling Machines", parentId: "dds184" },
  { id: "dds187", name: "Knee Mills", parentId: "dds184" },
  { id: "dds188", name: "CNC Milling Machines", parentId: "dds184" },
  { id: "dds189", name: "Turning Machines (Lathes)", parentId: "dds163" },
  { id: "dds190", name: "Engine Lathes", parentId: "dds189" },
  { id: "dds191", name: "Bench Lathes", parentId: "dds189" },
  { id: "dds192", name: "CNC Lathes", parentId: "dds189" },
  { id: "dds193", name: "Toolroom Lathes", parentId: "dds189" },
  { id: "dds194", name: "Sawing Machines", parentId: "dds163" },
  { id: "dds195", name: "Horizontal Band Saws", parentId: "dds194" },
  { id: "dds196", name: "Vertical Band Saws", parentId: "dds194" },
  { id: "dds197", name: "Cold Saws", parentId: "dds194" },
  { id: "dds198", name: "Circular Saw Machines", parentId: "dds194" },
  { id: "dds199", name: "Specialty & Production Machines", parentId: "dds163" },
  { id: "dds200", name: "Threading Machines", parentId: "dds199" },
  { id: "dds201", name: "Tapping Machines", parentId: "dds199" },
  { id: "dds202", name: "Broaching Machines", parentId: "dds199" },
  { id: "dds203", name: "Slotting Machines", parentId: "dds199" },

  // Storage & Workspace
  { id: "dds204", name: "Storage & Workspace", parentId: "" },
  { id: "dds205", name: "Tool Storage", parentId: "dds204" },
  { id: "dds206", name: "Toolboxes", parentId: "dds205" },
  { id: "dds207", name: "Tool Chests", parentId: "dds205" },
  { id: "dds208", name: "Tool Cabinets", parentId: "dds205" },
  { id: "dds209", name: "Small Parts Organizers", parentId: "dds205" },
  { id: "dds210", name: "Drawer Storage Units", parentId: "dds205" },
  { id: "dds211", name: "Modular Storage Systems", parentId: "dds204" },
  { id: "dds212", name: "Stackable Tool Cases", parentId: "dds211" },
  { id: "dds213", name: "Rolling Base Units", parentId: "dds211" },
  { id: "dds214", name: "Modular Organizers", parentId: "dds211" },
  { id: "dds215", name: "System Mounting Plates", parentId: "dds211" },
  { id: "dds216", name: "System Rails & Accessories", parentId: "dds211" },
  { id: "dds217", name: "Mobile Storage & Carts", parentId: "dds204" },
  { id: "dds218", name: "Tool Carts", parentId: "dds217" },
  { id: "dds219", name: "Service Carts", parentId: "dds217" },
  { id: "dds220", name: "Rolling Tool Cabinets", parentId: "dds217" },
  { id: "dds221", name: "Utility Carts", parentId: "dds217" },
  { id: "dds222", name: "Shop Equipment", parentId: "dds204" },
  { id: "dds223", name: "Jobsite Lights", parentId: "dds222" },
  { id: "dds224", name: "Work Lights", parentId: "dds222" },
  { id: "dds225", name: "Tripod Lights", parentId: "dds222" },
  { id: "dds226", name: "Radios", parentId: "dds222" },
  { id: "dds227", name: "Fans", parentId: "dds222" },
  { id: "dds228", name: "Stands & Tripods", parentId: "dds222" },

  // Safety & Workwear
  { id: "dds229", name: "Safety & Workwear", parentId: "" },
  { id: "dds230", name: "Head Protection", parentId: "dds229" },
  { id: "dds231", name: "Hard Hats", parentId: "dds230" },
  { id: "dds232", name: "Bump Caps", parentId: "dds230" },
  { id: "dds233", name: "Eye & Face Protection", parentId: "dds229" },
  { id: "dds234", name: "Safety Glasses", parentId: "dds233" },
  { id: "dds235", name: "Goggles", parentId: "dds233" },
  { id: "dds236", name: "Face Shields", parentId: "dds233" },
  { id: "dds237", name: "Welding Helmets", parentId: "dds233" },
  { id: "dds238", name: "Hearing Protection", parentId: "dds229" },
  { id: "dds239", name: "Earplugs", parentId: "dds238" },
  { id: "dds240", name: "Earmuffs", parentId: "dds238" },
  { id: "dds241", name: "Hand Protection", parentId: "dds229" },
  { id: "dds242", name: "Work Gloves", parentId: "dds241" },
  { id: "dds243", name: "Cut-Resistant Gloves", parentId: "dds241" },
  { id: "dds244", name: "Impact Gloves", parentId: "dds241" },
  { id: "dds245", name: "Chemical-Resistant Gloves", parentId: "dds241" },
  { id: "dds246", name: "Protective Clothing & Workwear", parentId: "dds229" },
  { id: "dds247", name: "Work Pants", parentId: "dds246" },
  { id: "dds248", name: "Work Shirts", parentId: "dds246" },
  { id: "dds249", name: "Jackets & Coats", parentId: "dds246" },
  { id: "dds250", name: "Hi-Vis Apparel", parentId: "dds246" },
  { id: "dds251", name: "FR Clothing", parentId: "dds246" },
  { id: "dds252", name: "Foot Protection", parentId: "dds229" },
  { id: "dds253", name: "Safety Boots", parentId: "dds252" },
  { id: "dds254", name: "Safety Shoes", parentId: "dds252" },
  { id: "dds255", name: "Toe Guards", parentId: "dds252" },
  { id: "dds256", name: "Fall Protection", parentId: "dds229" },
  { id: "dds257", name: "Safety Harnesses", parentId: "dds256" },
  { id: "dds258", name: "Lanyards", parentId: "dds256" },
  { id: "dds259", name: "Anchors", parentId: "dds256" },
  { id: "dds260", name: "Self-Retracting Lifelines", parentId: "dds256" },
  { id: "dds261", name: "Respiratory Protection", parentId: "dds229" },
  { id: "dds262", name: "Disposable Respirators", parentId: "dds261" },
  { id: "dds263", name: "Reusable Respirators", parentId: "dds261" },
  { id: "dds264", name: "Respirator Cartridges", parentId: "dds261" },
  { id: "dds265", name: "Filters", parentId: "dds261" },
  { id: "dds266", name: "Jobsite Safety Equipment", parentId: "dds229" },
  { id: "dds267", name: "Safety Cones", parentId: "dds266" },
  { id: "dds268", name: "Barricades", parentId: "dds266" },
  { id: "dds269", name: "Caution Tape", parentId: "dds266" },
  { id: "dds270", name: "Safety Signage", parentId: "dds266" },
  { id: "dds271", name: "Tool Carrying & Wearable Accessories", parentId: "dds229" },
  { id: "dds272", name: "Tool Belts", parentId: "dds271" },
  { id: "dds273", name: "Tool Pouches", parentId: "dds271" },
  { id: "dds274", name: "Tool Holsters", parentId: "dds271" },
  { id: "dds275", name: "Tool Lanyards", parentId: "dds271" },
  { id: "dds276", name: "Suspenders", parentId: "dds271" },

  // Jobsite Supplies & Material Handling
  { id: "dds277", name: "Jobsite Supplies & Material Handling", parentId: "" },
  { id: "dds278", name: "Material Handling Equipment", parentId: "dds277" },
  { id: "dds279", name: "Hand Trucks", parentId: "dds278" },
  { id: "dds280", name: "Dollies", parentId: "dds278" },
  { id: "dds281", name: "Platform Carts", parentId: "dds278" },
  { id: "dds282", name: "Pallet Jacks", parentId: "dds278" },
  { id: "dds283", name: "Lifting Slings", parentId: "dds278" },
  { id: "dds284", name: "Hoists", parentId: "dds278" },
  { id: "dds285", name: "Ladders & Access Equipment", parentId: "dds277" },
  { id: "dds286", name: "Step Ladders", parentId: "dds285" },
  { id: "dds287", name: "Extension Ladders", parentId: "dds285" },
  { id: "dds288", name: "Platform Ladders", parentId: "dds285" },
  { id: "dds289", name: "Folding Ladders", parentId: "dds285" },
  { id: "dds290", name: "Jobsite Consumables", parentId: "dds277" },
  { id: "dds291", name: "Marking Paint (Spray)", parentId: "dds290" },
  { id: "dds292", name: "Lubricants", parentId: "dds290" },
  { id: "dds293", name: "Threadlock Compounds", parentId: "dds290" },
  { id: "dds294", name: "Cleaners & Degreasers", parentId: "dds290" },
  { id: "dds295", name: "Wipes", parentId: "dds290" },
  { id: "dds296", name: "Tapes, Adhesives & Sealants", parentId: "dds277" },
  { id: "dds297", name: "Duct Tape", parentId: "dds296" },
  { id: "dds298", name: "Electrical Tape", parentId: "dds296" },
  { id: "dds299", name: "Construction Tape", parentId: "dds296" },
  { id: "dds300", name: "Adhesives", parentId: "dds296" },
  { id: "dds301", name: "Sealants", parentId: "dds296" },

  // Fasteners
  { id: "dds302", name: "Fasteners", parentId: "" },
  { id: "dds303", name: "Screws", parentId: "dds302" },
  { id: "dds304", name: "Wood Screws", parentId: "dds303" },
  { id: "dds305", name: "Construction Screws", parentId: "dds303" },
  { id: "dds306", name: "Structural Screws", parentId: "dds303" },
  { id: "dds307", name: "Deck Screws", parentId: "dds303" },
  { id: "dds308", name: "Pocket-Hole Screws", parentId: "dds303" },
  { id: "dds309", name: "Drywall Screws", parentId: "dds303" },
  { id: "dds310", name: "Sheet Metal Screws", parentId: "dds303" },
  { id: "dds311", name: "Self-Drilling Screws (TEK)", parentId: "dds303" },
  { id: "dds312", name: "Machine Screws", parentId: "dds303" },
  { id: "dds313", name: "Lag Screws (Lag Bolts)", parentId: "dds303" },
  { id: "dds314", name: "Concrete Screws", parentId: "dds303" },
  { id: "dds315", name: "Security Screws", parentId: "dds303" },
  { id: "dds316", name: "Set Screws (Grub Screws)", parentId: "dds303" },
  { id: "dds317", name: "Trim / Finish Screws", parentId: "dds303" },
  { id: "dds318", name: "Cement Board Screws", parentId: "dds303" },
  { id: "dds319", name: "Roofing Screws", parentId: "dds303" },
  { id: "dds320", name: "Thread-Forming Screws", parentId: "dds303" },
  { id: "dds321", name: "Thread-Cutting Screws", parentId: "dds303" },
  { id: "dds322", name: "Screw Assortments & Kits", parentId: "dds303" },
  { id: "dds323", name: "Bolts", parentId: "dds302" },
  { id: "dds324", name: "Hex Head Cap Screws / Hex Bolts", parentId: "dds323" },
  { id: "dds325", name: "Carriage Bolts", parentId: "dds323" },
  { id: "dds326", name: "Flange Bolts", parentId: "dds323" },
  { id: "dds327", name: "Structural Bolts", parentId: "dds323" },
  { id: "dds328", name: "Eye Bolts", parentId: "dds323" },
  { id: "dds329", name: "U-Bolts", parentId: "dds323" },
  { id: "dds330", name: "J-Bolts", parentId: "dds323" },
  { id: "dds331", name: "T-Bolts / T-Slot Bolts", parentId: "dds323" },
  { id: "dds332", name: "Anchor Bolts (Cast-In)", parentId: "dds323" },
  { id: "dds333", name: "Elevator Bolts", parentId: "dds323" },
  { id: "dds334", name: "Plow Bolts", parentId: "dds323" },
  { id: "dds335", name: "Shoulder Bolts", parentId: "dds323" },
  { id: "dds336", name: "Socket Head Cap Screws", parentId: "dds323" },
  { id: "dds337", name: "Button Head Socket Screws", parentId: "dds323" },
  { id: "dds338", name: "Flat Head Socket Screws", parentId: "dds323" },
  { id: "dds339", name: "Stud Bolts", parentId: "dds323" },
  { id: "dds340", name: "Bolt Assortments & Kits", parentId: "dds323" },
  { id: "dds341", name: "Nuts", parentId: "dds302" },
  { id: "dds342", name: "Hex Nuts", parentId: "dds341" },
  { id: "dds343", name: "Heavy Hex Nuts", parentId: "dds341" },
  { id: "dds344", name: "Jam Nuts", parentId: "dds341" },
  { id: "dds345", name: "Lock Nuts - Nylon Insert", parentId: "dds341" },
  { id: "dds346", name: "Lock Nuts - All-Metal", parentId: "dds341" },
  { id: "dds347", name: "Flange Nuts", parentId: "dds341" },
  { id: "dds348", name: "Cap (Acorn) Nuts", parentId: "dds341" },
  { id: "dds349", name: "Coupling Nuts", parentId: "dds341" },
  { id: "dds350", name: "Wing Nuts", parentId: "dds341" },
  { id: "dds351", name: "Square Nuts", parentId: "dds341" },
  { id: "dds352", name: "T-Nuts", parentId: "dds341" },
  { id: "dds353", name: "Weld Nuts", parentId: "dds341" },
  { id: "dds354", name: "Rivet Nuts (Nutserts)", parentId: "dds341" },
  { id: "dds355", name: "Cage Nuts", parentId: "dds341" },
  { id: "dds356", name: "Thumb / Knurled Nuts", parentId: "dds341" },
  { id: "dds357", name: "Slotted / Castle Nuts", parentId: "dds341" },
  { id: "dds358", name: "Washers", parentId: "dds302" },
  { id: "dds359", name: "Flat Washers", parentId: "dds358" },
  { id: "dds360", name: "Extra Thick Washers", parentId: "dds358" },
  { id: "dds361", name: "Fender Washers", parentId: "dds358" },
  { id: "dds362", name: "Split Lock Washers", parentId: "dds358" },
  { id: "dds363", name: "Tooth Lock Washers", parentId: "dds358" },
  { id: "dds364", name: "Sealing Washers", parentId: "dds358" },
  { id: "dds365", name: "Square Washers", parentId: "dds358" },
  { id: "dds366", name: "Dock / Plate Washers", parentId: "dds358" },
  { id: "dds367", name: "Concrete & Masonry Anchors", parentId: "dds302" },
  { id: "dds368", name: "Wedge Anchors", parentId: "dds367" },
  { id: "dds369", name: "Sleeve Anchors", parentId: "dds367" },
  { id: "dds370", name: "Drop-In Anchors", parentId: "dds367" },
  { id: "dds371", name: "Hammer Drive Anchors", parentId: "dds367" },
  { id: "dds372", name: "Machine Screw Anchors", parentId: "dds367" },
  { id: "dds373", name: "Lag Shield Anchors", parentId: "dds367" },
  { id: "dds374", name: "Expansion Shields", parentId: "dds367" },
  { id: "dds375", name: "Strike Anchors", parentId: "dds367" },
  { id: "dds376", name: "Pin Drive Anchors", parentId: "dds367" },
  { id: "dds377", name: "Drywall & Hollow Wall Anchors", parentId: "dds302" },
  { id: "dds378", name: "Toggle Bolts", parentId: "dds377" },
  { id: "dds379", name: "Strap Toggles", parentId: "dds377" },
  { id: "dds380", name: "Self-Drilling Drywall Anchors", parentId: "dds377" },
  { id: "dds381", name: "Hollow Wall Anchors", parentId: "dds377" },
  { id: "dds382", name: "Threaded Rod & Studs", parentId: "dds302" },
  { id: "dds383", name: "Threaded Rod (All-Thread)", parentId: "dds382" },
  { id: "dds384", name: "Fully Threaded Studs", parentId: "dds382" },
  { id: "dds385", name: "ACME Rod", parentId: "dds382" },
  { id: "dds386", name: "Rod Couplers", parentId: "dds382" },
  { id: "dds387", name: "Threaded Rod Accessories", parentId: "dds382" },
  { id: "dds388", name: "Rivets", parentId: "dds302" },
  { id: "dds389", name: "Blind Rivets", parentId: "dds388" },
  { id: "dds390", name: "Structural Blind Rivets", parentId: "dds388" },
  { id: "dds391", name: "Sealed / Closed-End Rivets", parentId: "dds388" },
  { id: "dds392", name: "Large Flange Rivets", parentId: "dds388" },
  { id: "dds393", name: "Multi-Grip Rivets", parentId: "dds388" },
  { id: "dds394", name: "Solid Rivets", parentId: "dds388" },
  { id: "dds395", name: "Drive Rivets", parentId: "dds388" },
  { id: "dds396", name: "Rivet Assortments", parentId: "dds388" },
  { id: "dds397", name: "Nails", parentId: "dds302" },
  { id: "dds398", name: "Common Nails", parentId: "dds397" },
  { id: "dds399", name: "Box Nails", parentId: "dds397" },
  { id: "dds400", name: "Framing Nails", parentId: "dds397" },
  { id: "dds401", name: "Finish Nails", parentId: "dds397" },
  { id: "dds402", name: "Brad Nails", parentId: "dds397" },
  { id: "dds403", name: "Pin Nails", parentId: "dds397" },
  { id: "dds404", name: "Roofing Nails", parentId: "dds397" },
  { id: "dds405", name: "Concrete / Masonry Nails", parentId: "dds397" },
  { id: "dds406", name: "Joist Hanger Nails", parentId: "dds397" },
  { id: "dds407", name: "Coil Nails", parentId: "dds397" },
  { id: "dds408", name: "Collated Nails", parentId: "dds397" },
  { id: "dds409", name: "Construction & Structural Connectors", parentId: "dds302" },
  { id: "dds410", name: "Joist Hangers", parentId: "dds409" },
  { id: "dds411", name: "Hurricane Ties", parentId: "dds409" },
  { id: "dds412", name: "Angles & Angle Brackets", parentId: "dds409" },
  { id: "dds413", name: "Straps & Ties", parentId: "dds409" },
  { id: "dds414", name: "Plates", parentId: "dds409" },
  { id: "dds415", name: "Post Bases", parentId: "dds409" },
  { id: "dds416", name: "Post Caps", parentId: "dds409" },
  { id: "dds417", name: "Holdowns", parentId: "dds409" },
  { id: "dds418", name: "Column Caps", parentId: "dds409" },
  { id: "dds419", name: "Rafter & Ridge Connectors", parentId: "dds409" },
  { id: "dds420", name: "Truss Connectors", parentId: "dds409" },
  { id: "dds421", name: "Deck Connectors", parentId: "dds409" },
  { id: "dds422", name: "Wood-to-Concrete Connectors", parentId: "dds409" },
  { id: "dds423", name: "Specialty & Miscellaneous Fasteners", parentId: "dds302" },
  { id: "dds424", name: "Retaining Rings", parentId: "dds423" },
  { id: "dds425", name: "Cotter Pins", parentId: "dds423" },
  { id: "dds426", name: "Dowel Pins", parentId: "dds423" },
  { id: "dds427", name: "Spring Pins (Roll Pins)", parentId: "dds423" },
  { id: "dds428", name: "Clevis Pins", parentId: "dds423" },
  { id: "dds429", name: "Hitch Pins", parentId: "dds423" },
  { id: "dds430", name: "E-Clips / Snap Rings", parentId: "dds423" },
  { id: "dds431", name: "Clips & Retainers", parentId: "dds423" },
  { id: "dds432", name: "Concrete Pins (Powder-Actuated)", parentId: "dds423" },
  { id: "dds433", name: "Thread Inserts", parentId: "dds423" },
  { id: "dds434", name: "Spacers & Standoffs", parentId: "dds423" },
  { id: "dds435", name: "Miscellaneous Fastener Kits", parentId: "dds423" },

  // Strut & Accessories
  { id: "dds436", name: "Strut & Accessories", parentId: "" },
  { id: "dds437", name: "Strut Channel", parentId: "dds436" },
  { id: "dds438", name: "Standard Strut Channel", parentId: "dds437" },
  { id: "dds439", name: "Shallow Strut Channel", parentId: "dds437" },
  { id: "dds440", name: "Back-to-Back Strut Channel", parentId: "dds437" },
  { id: "dds441", name: "Double Strut Channel", parentId: "dds437" },
  { id: "dds442", name: "Solid (Plain) Strut Channel", parentId: "dds437" },
  { id: "dds443", name: "Angle & Flat Fittings", parentId: "dds436" },
  { id: "dds444", name: "90° Angle Fittings", parentId: "dds443" },
  { id: "dds445", name: "Flat Plate Fittings", parentId: "dds443" },
  { id: "dds446", name: "Offset Fittings", parentId: "dds443" },
  { id: "dds447", name: "Tee & Cross Fittings", parentId: "dds436" },
  { id: "dds448", name: "Tee Fittings", parentId: "dds447" },
  { id: "dds449", name: "Cross Fittings", parentId: "dds447" },
  { id: "dds450", name: "Four-Hole Fittings", parentId: "dds447" },
  { id: "dds451", name: "Structural Brackets", parentId: "dds436" },
  { id: "dds452", name: "Corner Brackets", parentId: "dds451" },
  { id: "dds453", name: "Gussets", parentId: "dds451" },
  { id: "dds454", name: "Channel Brackets", parentId: "dds451" },
  { id: "dds455", name: "Mounting Plates", parentId: "dds451" },
  { id: "dds456", name: "Beam & Structural Attachments", parentId: "dds436" },
  { id: "dds457", name: "Beam Clamps", parentId: "dds456" },
  { id: "dds458", name: "Girder Clamps", parentId: "dds456" },
  { id: "dds459", name: "Structural Clips", parentId: "dds456" },
  { id: "dds460", name: "Channel Nuts", parentId: "dds436" },
  { id: "dds461", name: "Spring Channel Nuts", parentId: "dds460" },
  { id: "dds462", name: "Regular Channel Nuts", parentId: "dds460" },
  { id: "dds463", name: "Cone Channel Nuts", parentId: "dds460" },
  { id: "dds464", name: "Coil Channel Nuts", parentId: "dds460" },
  { id: "dds465", name: "Strut Washers", parentId: "dds436" },
  { id: "dds466", name: "Strut Washers", parentId: "dds465" },
  { id: "dds467", name: "End Caps", parentId: "dds436" },
  { id: "dds468", name: "Regular End Caps", parentId: "dds467" },
  { id: "dds469", name: "Low Profile End Caps", parentId: "dds467" },
  { id: "dds470", name: "Joining & Bracing", parentId: "dds436" },
  { id: "dds471", name: "Splice Plates", parentId: "dds470" },
  { id: "dds472", name: "Channel Joiners", parentId: "dds470" },
  { id: "dds473", name: "Bracing Plates", parentId: "dds470" },
  { id: "dds474", name: "Seismic Bracing Components", parentId: "dds470" },
  { id: "dds475", name: "Pipe & Conduit Supports", parentId: "dds436" },
  { id: "dds476", name: "Pipe Clamps", parentId: "dds475" },
  { id: "dds477", name: "Clevis Hangers", parentId: "dds475" },
  { id: "dds478", name: "Riser Clamps", parentId: "dds475" },
  { id: "dds479", name: "Conduit Clamps", parentId: "dds475" },
  { id: "dds480", name: "Strut-Mounted Conduit Hangers", parentId: "dds475" },
  { id: "dds481", name: "U-Bolt Assemblies", parentId: "dds475" },
  { id: "dds482", name: "Strut Trolleys", parentId: "dds436" },
  { id: "dds483", name: "Strut Trolleys", parentId: "dds482" },
  { id: "dds484", name: "Post Bases", parentId: "dds436" },
  { id: "dds485", name: "Post Bases", parentId: "dds484" },
];

export const categoryTree: CategoryNode[] = buildTree(rawCategories);

// Flat lookup for finding a category by slug
export function findCategoryBySlug(slug: string, nodes: CategoryNode[] = categoryTree): CategoryNode | null {
  for (const node of nodes) {
    if (node.slug === slug) return node;
    const found = findCategoryBySlug(slug, node.children);
    if (found) return found;
  }
  return null;
}

// Get all descendant names (for filtering products)
export function getAllDescendantNames(node: CategoryNode): string[] {
  const names = [node.name];
  for (const child of node.children) {
    names.push(...getAllDescendantNames(child));
  }
  return names;
}
